"use client"
import {createContext,useCallback,useContext,useEffect,useMemo,useRef,useState} from 'react';
import {getWebSocketClient} from '@/lib/websocket-client';

type ConnectionState='DISCONNECTED'|'CONNECTING'|'READY'|'RECONNECTING'|'FAILED';
type DeviceSessionState={deviceId:number;sessionId?:string;protocol?:string;connectionState:ConnectionState;connectedAt?:string;lastUpdateAt?:string;latencyMs?:number;errorCode?:string;errorMessage?:string;capabilities:string[];snapshot?:Record<string,unknown>;refresh:()=>void};
const Context=createContext<DeviceSessionState|null>(null);
export function DeviceSessionProvider({deviceId,children}:{deviceId:number;children:React.ReactNode}){const [state,setState]=useState<Omit<DeviceSessionState,'refresh'>>({deviceId,connectionState:'CONNECTING',capabilities:[]}),requestId=useRef(0);
 const send=useCallback((type:string,extra:Record<string,unknown>={})=>{const client=getWebSocketClient();client?.send({type,data:{deviceId,requestId:`device-${deviceId}-${++requestId.current}`,...extra}})},[deviceId]);
 const open=useCallback(()=>{setState(current=>({...current,connectionState:'CONNECTING'}));send('device:room:join');send('device:session:open',{requestedProtocol:'AUTO'});send('device:dashboard:subscribe')},[send]);
 const refresh=useCallback(()=>send('device:dashboard:refresh'),[send]);
 useEffect(()=>{const client=getWebSocketClient();if(!client)return;let active=true;const ready=(data:any)=>{if(!active||Number(data?.deviceId)!==deviceId)return;setState(current=>({...current,sessionId:data.sessionId||current.sessionId,protocol:data.protocol||current.protocol,connectionState:'READY',connectedAt:data.connectedAt||current.connectedAt,errorCode:undefined,errorMessage:undefined}))};const snapshot=(data:any)=>{if(!active||Number(data?.deviceId)!==deviceId)return;setState(current=>({...current,sessionId:data.sessionId||current.sessionId,protocol:data.protocol||current.protocol,connectionState:'READY',snapshot:data.data,lastUpdateAt:data.timestamp||new Date().toISOString()}))};const update=(data:any)=>{if(!active||Number(data?.deviceId)!==deviceId)return;setState(current=>({...current,snapshot:{...(current.snapshot||{}),health:data.data},lastUpdateAt:data.timestamp||new Date().toISOString()}))};const failed=(data:any)=>{if(!active||Number(data?.deviceId)!==deviceId)return;setState(current=>({...current,connectionState:'FAILED',errorCode:data.errorCode,errorMessage:data.message}))};const reconnect=()=>setState(current=>({...current,connectionState:'RECONNECTING'}));const removers=[client.on('authenticated',open),client.on('device:connection:ready',ready),client.on('device:dashboard:snapshot',snapshot),client.on('device:health:update',update),client.on('device:connection:error',failed),client.on('disconnected',reconnect),client.on('connected',()=>{if(client.isAuthenticated())open()})];client.connect().then(()=>{if(client.isAuthenticated())open()}).catch(()=>setState(current=>({...current,connectionState:'FAILED',errorCode:'WEBSOCKET_UNAVAILABLE',errorMessage:'Live device channel is unavailable.'})));return()=>{active=false;send('device:dashboard:unsubscribe');send('device:room:leave');removers.forEach(remove=>remove())}},[deviceId,open,send]);
 const value=useMemo(()=>({...state,refresh}),[state,refresh]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useDeviceSession(){const value=useContext(Context);if(!value)throw new Error('useDeviceSession must be used inside DeviceSessionProvider.');return value}
