export type AgentStatus="ACTIVE"|"PAUSED"|"BUSY"|"OFFLINE"|"DRAFT";
export type AiAgent={id:number;slug:string;name:string;role:string;department:string;description:string;status:AgentStatus;icon:string;modules:string[];tools:string[];sensitiveActions:string[];suggestedPrompts:string[]};
const rows:any[]=[
["manager","Manager AI","AI Workforce Orchestrator","AI Operations","Bot",["AI Agents","Workflows","Approvals","Tasks","Reports"],[]],
["noc","NOC AI Agent","Virtual NOC Engineer","Network Operations","Activity",["Network","NOC","Devices","OLT","ONT","Radius","Incidents","Automation"],["getNetworkAlarms","getDeviceHealth","getRadiusSession","getOLTStatus","runDiagnostic"]],
["support","Support AI Agent","Virtual Customer Support Representative","Customer Support","Headphones",["CRM","Customers","Support","Tickets","Billing","Radius"],["getCustomer","getCustomerBalance","getRadiusSession","getONTStatus","createTicket"]],
["billing","Billing AI Agent","Virtual Billing Officer","Billing","Receipt",["Billing","Invoices","Customers","Payments","Taxes","Reports"],["getInvoice","explainInvoice","calculateProration","createCreditNote"]],
["collections","Collections AI Agent","Virtual Collections Officer","Collections","WalletCards",["Billing","Payments","Collections","Customers","Notifications","Reports"],["getCustomerBalance","createPaymentLink","getCollectionSummary"]],
["finance","Finance AI Agent","Virtual Finance Analyst","Finance","ChartNoAxesCombined",["Finance","Payments","Settlements","Reconciliation","Reports"],["reconcilePayment","getRevenueSummary","getCollectionSummary"]],
["sales","Sales AI Agent","Virtual Sales Executive","Sales","TrendingUp",["CRM","Leads","Customers","Products","Coverage","Orders"],["searchCustomers","getCustomerServices","createAutomationTask"]],
["retention","Retention AI Agent","Virtual Customer Retention Specialist","Customer Success","UserRoundCheck",["CRM","Customers","Usage","Support","Campaigns","Reports"],["getCustomer","getChurnSummary","getSupportPerformance"]],
["field-operations","Field Operations AI Agent","Virtual Field Operations Dispatcher","Field Operations","Wrench",["Work Orders","Technicians","Inventory","Customers","Maps"],["createWorkOrder","assignTechnician","reserveInventory"]],
["inventory","Inventory AI Agent","Virtual Inventory Controller","Inventory","Package",["Inventory","Warehouses","Procurement","Vendors","Devices"],["getInventory","reserveInventory","transferInventory","getDeviceBySerial"]],
["provisioning","Provisioning AI Agent","Virtual Provisioning Engineer","Service Fulfillment","Cable",["Orders","Provisioning","Network","Radius","OLT","ONT","Automation"],["getDeviceHealth","runDiagnostic","executeApprovedWorkflow"]],
["hardware-automation","Hardware Automation AI Agent","Virtual Network Automation Engineer","Network Engineering","Network",["Devices","Network","Automation","Reports"],["getDevice","getDeviceHealth","runDiagnostic","rollbackWorkflow"]],
["voice","Voice AI Agent","Virtual Voice Representative","Customer Engagement","AudioLines",["CRM","Customers","Billing","Support","Voice"],["getCustomer","createPaymentLink","createTicket"]],
["chat","Chat AI Agent","Virtual Chat Representative","Customer Engagement","MessageSquare",["CRM","Customers","Billing","Support","Chat"],["getCustomer","getCustomerBalance","createTicket"]],
["ceo","CEO AI Agent","Virtual Executive Assistant","Executive Management","BriefcaseBusiness",["Reports","Analytics","Finance","Billing","Network","Support","Sales"],["getRevenueSummary","getCollectionSummary","getNetworkAvailability","getSupportPerformance"]]
];
export const defaultAgents:AiAgent[]=rows.map((r,i)=>({id:i+1,slug:r[0],name:r[1],role:r[2],department:r[3],icon:r[4],modules:r[5],tools:r[6],description:`${r[2]} constrained to approved ${r[3]} data, tools, and workflows.`,status:"ACTIVE",sensitiveActions:["Write or execute action","Financial or customer-impacting change","Configuration change"],suggestedPrompts:r[0]==="noc"?["Show current critical alarms","Which customers are affected?","Check OLT health"]:r[0]==="billing"?["Explain this invoice","Find billing anomalies","Calculate proration"]:r[0]==="ceo"?["Give me today's business briefing","Show major risks","Compare branches"]:[`Show ${r[3].toLowerCase()} priorities`,`Summarize recent activity`,`Recommend next actions`]}));
export const agentSections=["dashboard","directory","tasks","approvals","activity","conversations","tools","knowledge","permissions","analytics","usage","audit-logs","versions","settings"] as const;
